CREATE TABLE "GCG_5885_VEND_CERTS" IN DICTIONARY USING 'GCG_5885_VEND_CERTS.mkd' PAGESIZE=4096 (
 "VENDOR" CHAR(6),
 "CERTIFICATION" CHAR(150),
 "START_DATE" DATE,
 "END_DATE" DATE,
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0 );