CREATE TABLE "GCG_5885_BI_CERT" (
 "VENDOR" CHAR(6),
 "CERTIFICATION" LONGVARCHAR,
 "PURCHASE_ORDER" CHAR(7),
 "INVOICE" CHAR(15),
 "DATE_INVOICE" DATE,
 "DATE_INVOICE_DUE" DATE,
 "CHECK_NUM" CHAR(20),
 "DATE_CHECK" DATE,
 "AMT_TRANSACTION" DOUBLE,
 "TERMINAL" CHAR(3),
 "RPT_ID" INTEGER );
